Use templates instead of config

diff --git a/rootfs/etc/cont-init.d/02-extra-packages b/rootfs/etc/cont-init.d/02-extra-packages
--- a/rootfs/etc/cont-init.d/02-extra-packages
+++ b/rootfs/etc/cont-init.d/02-extra-packages
@@ -1,22 +1,22 @@
 #!/usr/bin/with-contenv bash
 
 # check if user passed in list of repositories
-if [ -n "$REPOSITORIES" ]; then
-  echo "User passed in extra repositories to add"
-  IFS=',' read -r -a repos <<< $REPOSITORIES
-  for repo in "${repos[@]}"; do
-    # check to see if repo is already included
-    echo $repo >> /etc/apk/repositories
-  done
-fi
+# if [ -n "$REPOSITORIES" ]; then
+#   echo "User passed in extra repositories to add"
+#   IFS=',' read -r -a repos <<< $REPOSITORIES
+#   for repo in "${repos[@]}"; do
+#     # check to see if repo is already included
+#     echo $repo >> /etc/apk/repositories
+#   done
+# fi
 
 # check if user asked for extra packages
-if [ -n "$EXTRA_PACKAGES" ]; then
-  echo "About to install packages"
-  packages=${EXTRA_PACKAGES//,/ }
-  apk add --update $packages
-  if [ $? -ne 0 ]; then
-    echo "There was an error while installig packages"
-    exit 1
-  fi
-fi
+# if [ -n "$EXTRA_PACKAGES" ]; then
+#   echo "About to install packages"
+#   packages=${EXTRA_PACKAGES//,/ }
+#   apk add --update $packages
+#   if [ $? -ne 0 ]; then
+#     echo "There was an error while installig packages"
+#     exit 1
+#   fi
+# fi
